# Generated by Django 4.2 on 2024-06-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_client'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscrition',
            new_name='Subscription',
        ),
    ]
