# Generated by Django 4.2 on 2024-06-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fill_address',
            new_name='full_address',
        ),
    ]
